### PR TITLE
Add Docker setup and testing documentation

### PR DESCRIPTION
**Pull request by Adesoji1**
- Created Dockerfile, entrypoint.sh, picture folder and .dockerignore in the root directory
- Added test.md with detailed instructions on Docker setup and how to test the Docker container
- Documented all testing procedures within test.md
- Included a screenshot of the successful Docker build and test of docker container run  in the pictures folder

### CODE REVIEW

**Review by mostafaelhoushi — APPROVED** [review]
Thank you @Adesoji1 for working on this great feature! I highly appreciate that.
I am personally not familiar with Docker so it is great you added this functionality.

Happy to merge this PR but I am wondering if you would like to add to the README a small section about the Docker and point it to "test.md"?

I am not familiar with the conventions of Docker instructions, but was wondering if it is a good idea to rename `test.md` to `docker.md` or `DOCKER.md`?

Thanks again!

**Comment by Adesoji1** [comment]
Thank you @mostafaelhoushi . Yes, I could do that, I will reference the
docker instructions to run the project and also rename test.md to docker.md
in another pull request so you could merge, is this ok with you? In
addition, Docker ensures that the application could be packaged into a
container. containers offer a high level of isolation between applications
and their dependencies. Each container runs independently, which means that
it will not interfere with other containers on the same machine or server.
This is crucial to ensure the security and stability of applications in
shared environments.

**Comment by mostafaelhoushi** [comment]
Sure @Adesoji1 ! Thanks for explaining the importance of dockers. I just merged the PR.
So you can create a separate PR. Also do you think it's a good idea to name the file with upper case letters (DOCKER.md) to be consistent with the existing README.md file?

**Comment by Adesoji1** [comment]
Sure @mostafaelhoushi, I will do just that, Thank you

**Pull request merged**
